package Nacre::App;
# ABSTRACT: CLI app

use v5.36;
use namespace::autoclean;
use FindBin;
use Moo;
use CLI::Osprey;
use MooX::ShortHas;

use Nacre::Perl5::Repo;
use Path::Tiny qw(path);
use List::UtilsBy qw(partition_by sort_by);

use Nacre::Perl5::Opcode::ToProlog;
use Template;

option perl5_git_path => (
	is      => 'ro',
	format  => 's',
	default => sub {
		path($FindBin::Bin, '..', 'vendor/Perl/perl5/.git')
	},
);

lazy repo => sub ($self) {
	Nacre::Perl5::Repo->new(
		gitdir => $self->perl5_git_path,
	);
};

lazy versions => sub ($self) {
	$self->repo->perl5_versions;
};

lazy versions_filtered => sub ($self) {
	my %partitions = partition_by { $_->version_two_digit }
		$self->versions->@*;
	my @versions_filtered =
		grep { ($_->version->normal =~ /v\d+\.(\d+)/)[0] % 2 == 0 }
		sort_by { $_->version }
		map {
			my $p = $_;
			my @sorted = sort_by { $_->version } @$p;
			$sorted[-1];
		}
		values %partitions;
	\@versions_filtered;
};

sub run ($self) {
	die <<~'EOF' unless -d $self->perl5_git_path;
	Missing `perl5` checkout. Run:

	    make clone-perl5
	EOF

	my $tt2 = Template->new;

	my $gen_perl_logtalk_dir = path('src/perl/version');
	my $gen_perl_tt2_file = $gen_perl_logtalk_dir->child('perl_v.lgt.tt2');
	-f $gen_perl_tt2_file or die "Missing template $gen_perl_tt2_file";

	my $gen_opcode_dir = path('GENERATED')->child(qw(src perl opcode));

	my @perl_logtalk_files;
	for my $v ($self->versions_filtered->@*) {
		my $file_basename = 'perl_' . $v->version_two_digit =~ s/\./_/gr;

		my $gen_opcode_file = $gen_opcode_dir->child("$file_basename.pl");
		my $to_prolog = Nacre::Perl5::Opcode::ToProlog->new(
			perl_version => $v,
		);
		$gen_opcode_file->parent->mkdir;
		$gen_opcode_file->spew_utf8($to_prolog->as_prolog_facts);

		my $gen_perl_logtalk_file = $gen_perl_logtalk_dir->child("$file_basename.lgt");
		push @perl_logtalk_files, $gen_perl_logtalk_file;
		$tt2->process("$gen_perl_tt2_file", {
			perl_version => $v->version_two_digit
		}, "$gen_perl_logtalk_file") or die $tt2->error;
	}

	$gen_perl_logtalk_dir->child('loader.lgt')->spew_utf8(<<~EOF
		% DO NOT EDIT!
		%
		% Generated by \`@{[ __PACKAGE__ ]}\`.
		:- initialization(
			logtalk_load([ @{[ qq<\n>.
				join qq<,\n>,
					map {
						my $bn = $_->basename('.lgt');
						"\t"x2 . "'$bn'"
					} @perl_logtalk_files ]}%,
			], [source_data(on)])
		).
		EOF
	);
}

1;
