package Nacre::App::Generate;
# ABSTRACT: Generate derived code and data

use v5.36;
use namespace::autoclean;
use Moo;
use CLI::Osprey;
use MooX::ShortHas;

use Nacre::Perl5::Opcode::ToProlog;
use Template;

for my $name (qw(project_root versions_filtered)) {
	lazy $name => sub ($self) { $self->parent_command->$name }
}

sub generate_prolog($self) {
	my $tt2 = Template->new({
		INCLUDE_PATH => $self->project_root,
	});

	my $gen_perl_logtalk_dir = $self->project_root->child(qw(src perl version));
	my $gen_perl_tt2_file = $gen_perl_logtalk_dir->child('perl_v.lgt.tt2');
	-f $gen_perl_tt2_file or die "Missing template $gen_perl_tt2_file";

	my $gen_opcode_dir = $self->project_root->child(qw(GENERATED src perl opcode));

	my @perl_logtalk_files;
	for my $v ($self->versions_filtered->@*) {
		my $file_basename = 'perl_' . $v->version_two_digit =~ s/\./_/gr;

		my $gen_opcode_file = $gen_opcode_dir->child("$file_basename.pl");
		my $to_prolog = Nacre::Perl5::Opcode::ToProlog->new(
			perl_version => $v,
		);
		$gen_opcode_file->parent->mkdir;
		$gen_opcode_file->spew_utf8($to_prolog->as_prolog_facts);

		my $gen_perl_logtalk_file = $gen_perl_logtalk_dir->child("$file_basename.lgt");
		push @perl_logtalk_files, $gen_perl_logtalk_file;
		$tt2->process("@{[ $gen_perl_tt2_file->relative($self->project_root) ]}", {
			perl_version => $v->version_two_digit
		}, "$gen_perl_logtalk_file") or die $tt2->error;
	}

	$gen_perl_logtalk_dir->child('loader.lgt')->spew_utf8(<<~EOF
		% DO NOT EDIT!
		%
		% Generated by \`@{[ __PACKAGE__ ]}\`.
		:- initialization(
			logtalk_load([ @{[ qq<\n>.
				join qq<,\n>,
					map {
						my $bn = $_->basename('.lgt');
						"\t"x2 . "'$bn'"
					} @perl_logtalk_files ]}%,
			], [source_data(on)])
		).
		EOF
	);
}

sub run ($self) {
	$self->generate_prolog;
}

1;
