package Nacre::Perl5::Opcode::ToProlog;
# ABSTRACT: Converts an opcode table to Prolog

use v5.36;
use Moo;
use MooX::ShortHas;
use Types::Common qw(InstanceOf);
use Nacre::Prolog::Sugar qw(A AL);

use Language::Prolog::Sugar functors => [qw(opcode)];

ro perl_version => (
	isa => InstanceOf['Nacre::Perl5::Version'],
);

lazy as_prolog_facts => sub ($self) {
	my $s = '';
	$s .= <<~EOF;
	% DO NOT EDIT!
	%
	% Generated by \`@{[ __PACKAGE__ ]}\`.
	%   - perl_version: @{[ $self->perl_version->version_two_digit ]}
	@{[ '%'x80 ]}
	EOF

	for my $o ($self->perl_version->opcode_table->opcodes->@*) {
		my $t = opcode(
				A($o->name),
				A($o->number),
				A($o->description),
				A($o->check_fnc),
				AL($o->flags_list->@*),
				AL($o->operands_list->@*)
			);
		$s .= "$t.\n";
	}

	$s;
};

1;
